apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversao-temperatura
spec:
  replicas: 2
  selector:
    matchLabels:
      app: conversao-temperatura
  template:
    metadata:
      labels:
        app: conversao-temperatura
    spec:
      containers:
      - name: conversao-temperatura
        image: vitorlinsbinski/guia-jenkins:{{tag}}
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: conversao-temperatura
spec:
  type: NodePort
  selector:
    app: conversao-temperatura
  ports:
    - port: 8080        # porta do service
      targetPort: 8080  # porta do container
      nodePort: 30080   # porta exposta pelo Minikube (30000-32767)